// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBClmFk5TUti1L9By77a9OUfmZ5Q2fivKY',
    appId: '1:968062576313:android:0add3014a6f11bc8959d68',
    messagingSenderId: '968062576313',
    projectId: 'parent-kid-finance',
    storageBucket: 'parent-kid-finance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNtdeDfNJodSI5oe0khivW3QkyHXayxBk',
    appId: '1:968062576313:ios:ad3ff3e5abaf3a7d959d68',
    messagingSenderId: '968062576313',
    projectId: 'parent-kid-finance',
    storageBucket: 'parent-kid-finance.appspot.com',
    iosClientId: '968062576313-kuga3ibsbndtova4982nns34g421p5c0.apps.googleusercontent.com',
    iosBundleId: 'k',
  );
}
